### ISSUE TITLE
Change db encoding to utf-8

### ISSUE THREAD

**Issue by filias** [filias/mac#30]

**Comment by paparomeo** [comment]
The database and all the tables have been converted to `utf8mb4` encoding and respective collation and the storage engine converted to InnoDB.

The database dumps before and after are in the project home directory in Python Anywhere (the conversion has already been applied to the live database so the dump file is only there for reference).

The database and tables encoding is now consistent and InnoDB should be a better storage engine.

Users should now be able to add :unicorn: and :rainbow: to their content.
